In [2]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Importing the dataset
df = pd.read_excel(r"C:\Users\NEW USER\Downloads\DSN_Bootcamp\DSN_Bootcamp Analytics Dataset.xlsx")

In [4]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip()
)
print(df.head())

   transaction_id       date store_id  state   channel product_category  \
0          100001 2026-05-25    AB-02  Abuja  WhatsApp             Home
1          100002 2026-04-17    LG-01  Lagos  WhatsApp      Electronics
2          100003 2026-02-26    AB-01  Abuja  WhatsApp      Electronics
3          100004 2026-06-09    KN-01   Kano    Online      Electronics
4          100005 2026-05-30    LG-01  Lagos    Online      Electronics

        product customer_id customer_type  units  unit_price_ngn  \
0  Standing Fan       C1141           New      1           58000
1    Smartphone       C1083     Returning      5          165000
2       Earbuds       C1029     Returning      3           32000
3    Power Bank       C1082     Returning      4           26000
4    Smartphone       C1180     Returning      1          165000

   discount_pct  revenue_reported_ngn  cost_per_unit_ngn return_flag sales_rep
0          0.00                 58000                NaN          No   Chinedu
1          0.05                627000           112000.0          No      Kemi
2          0.20                 76800            19000.0          No   Chinedu
3          0.00                104000            15000.0          No     Grace
4          0.05                156750           112000.0          No   Chinedu

In [5]:
# Validating unit_price and revenue_reported by product
df["expected_revenue_ngn"] = (
    df["units"]
    * df["unit_price_ngn"]
    * (1 - df["discount_pct"])
)

df["revenue_difference_ngn"] = (
    df["revenue_reported_ngn"]
    - df["expected_revenue_ngn"]
)

df["revenue_validation"] = np.where(
    np.isclose(df["revenue_difference_ngn"], 0),
    "PASS",
    "FAIL"
)

In [6]:
print(df[df["revenue_validation"] == "FAIL"])

     transaction_id       date store_id          state   channel  \
1            100002 2026-04-17    LG-01          Lagos  WhatsApp
15           100016 2026-07-25    LG-02          Lagos    Online
55           100056 2026-06-18    KN-01           Kano  In-store
66           100067 2026-07-07    AB-02          Abuja  WhatsApp
71           100072 2026-06-09    IB-01         Ibadan  In-store
91           100092 2026-05-11    PH-01  Port Harcourt  In-store
93           100094 2026-07-20    LG-02          Lagos  In-store
120          100121 2026-08-14    IB-01         Ibadan  In-store
162          100163 2026-06-26    KN-01           Kano    Online
171          100172 2026-03-29    IB-01         Ibadan  In-store
191          100192 2026-03-07    KN-01           Kano    Online
232          100233 2026-01-08    IB-01         Ibadan  In-store
234          100235 2026-05-22    IB-01         Ibadan  WhatsApp
258          100259 2026-07-23    AB-01          Abuja  In-store
277          100278 2026-06-27    LG-01          Lagos  In-store
283          100284 2026-08-11    AB-02          Abuja  In-store
293          100294 2026-07-20    IB-01         Ibadan  In-store
295          100296 2026-04-26    IB-01         Ibadan  WhatsApp
300          100301 2026-03-06    LG-02          Lagos  In-store
349          100350 2026-05-28    LG-01          Lagos  In-store
368          100369 2026-06-20    KN-01           Kano  WhatsApp
402          100403 2026-04-24    PH-01  Port Harcourt  In-store

    product_category          product customer_id customer_type  units  \
1        Electronics       Smartphone       C1083     Returning      5
15       Accessories        USB Cable       C1123           New      1
55       Accessories       Phone Case       C1187           New      1
66       Accessories         Backpack       C1157           New      3
71              Home     Standing Fan       C1058           New      3
91              Home          Blender       C1108     Returning      4
93              Home          Blender       C1036     Returning      4
120      Accessories       Phone Case       C1124           New      4
162      Electronics       Power Bank       C1158           New      5
171      Accessories         Backpack       C1172           New      2
191      Electronics       Smartphone       C1128     Returning      2
232      Accessories       Phone Case       C1097     Returning      3
234             Home  Electric Kettle       C1064           New      2
258      Electronics       Smartphone       C1033     Returning      1
277      Electronics       Power Bank       C1144           New      3
283             Home  Electric Kettle       C1115           New      4
293      Electronics       Power Bank       C1041           New      3
295      Electronics          Earbuds       C1170           New      2
300      Electronics       Power Bank       C1169     Returning      5
349             Home          Blender       C1110           New      3
368      Electronics       Power Bank       C1102     Returning      2
402             Home          Blender       C1149           New      3

     unit_price_ngn  discount_pct  revenue_reported_ngn  cost_per_unit_ngn  \
1            165000          0.05                627000           112000.0
15             6500          0.10                  4680             2200.0
55             9000          0.05                  6840             3500.0
66            28000          0.15                 57120            16000.0
71            58000          0.10                125280            39000.0
91            42000          0.10                166320            28000.0
93            42000          0.05                127680            28000.0
120            9000          0.00                 32400             3500.0
162           26000          0.15                 88400            15000.0
171           28000          0.15                 52360            16000.0
191          165000          0.10                267300           112000.0
232            9000          0.15                 27540             3500.0
234           24000          0.10                 38880            15000.0
258          165000          0.25                136125           112000.0
277           26000          0.10                 56160            15000.0
283           24000          0.10                 95040            15000.0
293           26000          0.10                 63180            15000.0
295           32000          0.05                 72960                NaN
300           26000          0.05                 98800            15000.0
349           42000          0.15                 96390            28000.0
368           26000          0.05                 59280            15000.0
402           42000          0.05                 95760            28000.0

    return_flag sales_rep  expected_revenue_ngn  revenue_difference_ngn  \
1            No      Kemi              783750.0               -156750.0
15           No      Kemi                5850.0                 -1170.0
55           No      Bola                8550.0                 -1710.0
66           No     David               71400.0                -14280.0
71           No     Grace              156600.0                -31320.0
91           No      Bola              151200.0                 15120.0
93           No    Fatima              159600.0                -31920.0
120          No      Bola               36000.0                 -3600.0
162          No      Bola              110500.0                -22100.0
171          No     David               47600.0                  4760.0
191          No     David              297000.0                -29700.0
232          No     David               22950.0                  4590.0
234          No     Aisha               43200.0                 -4320.0
258         Yes     Grace              123750.0                 12375.0
277          No    Fatima               70200.0                -14040.0
283          No    Fatima               86400.0                  8640.0
293          No    Fatima               70200.0                 -7020.0
295         Yes      Bola               60800.0                 12160.0
300         Yes     Aisha              123500.0                -24700.0
349          No    Fatima              107100.0                -10710.0
368          No      Bola               49400.0                  9880.0
402          No    Fatima              119700.0                -23940.0

    revenue_validation
1                 FAIL
15                FAIL
55                FAIL
66                FAIL
71                FAIL
91                FAIL
93                FAIL
120               FAIL
162               FAIL
171               FAIL
191               FAIL
232               FAIL
234               FAIL
258               FAIL
277               FAIL
283               FAIL
293               FAIL
295               FAIL
300               FAIL
349               FAIL
368               FAIL
402               FAIL

In [7]:
# Finding B — inconsistent State labels
df["state"] = df["state"].str.strip().str.title()
print(df['state'])

0       Abuja
1       Lagos
2       Abuja
3        Kano
4       Lagos
        ...
427      Kano
428    Ibadan
429     Lagos
430     Lagos
431    Ibadan
Name: state, Length: 432, dtype: object

In [8]:
df["duplicate_transaction"] = df["transaction_id"].duplicated(
    keep=False
)
print(df["duplicate_transaction"].value_counts())

duplicate_transaction
False    408
True      24
Name: count, dtype: int64

In [11]:
# To see the duplicate transactions
df.loc[
    df["duplicate_transaction"],
    "transaction_id"
].drop_duplicates().sort_values()

60     100061
73     100074
195    100196
196    100197
251    100252
275    100276
303    100304
305    100306
366    100367
385    100386
394    100395
400    100401
Name: transaction_id, dtype: int64

In [12]:
# How many times the transaction occured
df.loc[
    df["duplicate_transaction"],
    "transaction_id"
].value_counts().sort_index()

transaction_id
100061    2
100074    2
100196    2
100197    2
100252    2
100276    2
100304    2
100306    2
100367    2
100386    2
100395    2
100401    2
Name: count, dtype: int64

In [13]:
# Are the duplicated rows actually identical?
duplicate_ids = (
    df.loc[df["duplicate_transaction"], "transaction_id"]
    .drop_duplicates()
)

duplicate_records = (
    df[df["transaction_id"].isin(duplicate_ids)]
    .sort_values("transaction_id")
)

duplicate_records

,transaction_id,date,store_id,state,channel,product_category,product,customer_id,customer_type,units,...,discount_pct,revenue_reported_ngn,cost_per_unit_ngn,return_flag,sales_rep,expected_revenue_ngn,revenue_difference_ngn,revenue_validation,duplicate_transaction,category_validation
60,100061,2026-08-17,LG-02,Lagos,In-store,Electronics,Earbuds,C1039,Returning,1,...,0.15,27200,19000.0,No,Aisha,27200.0,0.0,PASS,True,PASS
430,100061,2026-08-17,LG-02,Lagos,In-store,Electronics,Earbuds,C1039,Returning,1,...,0.15,27200,19000.0,No,Aisha,27200.0,0.0,PASS,True,PASS
73,100074,2026-04-20,IB-01,Ibadan,In-store,Accessories,USB Cable,C1043,New,4,...,0.05,24700,2200.0,No,Chinedu,24700.0,0.0,PASS,True,PASS
428,100074,2026-04-20,IB-01,Ibadan,In-store,Accessories,USB Cable,C1043,New,4,...,0.05,24700,2200.0,No,Chinedu,24700.0,0.0,PASS,True,PASS
195,100196,2026-02-25,LG-02,Lagos,In-store,Electronics,Earbuds,C1147,Returning,4,...,0.10,115200,19000.0,No,Grace,115200.0,0.0,PASS,True,PASS
421,100196,2026-02-25,LG-02,Lagos,In-store,Electronics,Earbuds,C1147,Returning,4,...,0.10,115200,19000.0,No,Grace,115200.0,0.0,PASS,True,PASS
196,100197,2026-08-01,AB-01,Abuja,Online,Accessories,Phone Case,C1152,Returning,1,...,0.25,6750,3500.0,Yes,Kemi,6750.0,0.0,PASS,True,PASS
420,100197,2026-08-01,AB-01,Abuja,Online,Accessories,Phone Case,C1152,Returning,1,...,0.25,6750,3500.0,Yes,Kemi,6750.0,0.0,PASS,True,PASS
425,100252,2026-07-11,KN-01,Kano,In-store,Electronics,Power Bank,C1117,Returning,2,...,0.00,52000,15000.0,No,David,52000.0,0.0,PASS,True,PASS
251,100252,2026-07-11,KN-01,Kano,In-store,Electronics,Power Bank,C1117,Returning,2,...,0.00,52000,15000.0,No,David,52000.0,0.0,PASS,True,PASS
426,100276,2026-06-22,LG-02,Lagos,Online,Home,Electric Kettle,C1016,New,2,...,0.10,43200,15000.0,No,David,43200.0,0.0,PASS,True,PASS
275,100276,2026-06-22,LG-02,Lagos,Online,Home,Electric Kettle,C1016,New,2,...,0.10,43200,15000.0,No,David,43200.0,0.0,PASS,True,PASS
303,100304,2026-07-01,KN-01,Kano,WhatsApp,Home,Standing Fan,C1090,New,5,...,0.10,261000,39000.0,No,Bola,261000.0,0.0,PASS,True,PASS
422,100304,2026-07-01,KN-01,Kano,WhatsApp,Home,Standing Fan,C1090,New,5,...,0.10,261000,39000.0,No,Bola,261000.0,0.0,PASS,True,PASS
305,100306,2026-03-14,PH-01,Port Harcourt,In-store,Accessories,Phone Case,C1162,New,1,...,0.15,7650,3500.0,No,Aisha,7650.0,0.0,PASS,True,PASS
423,100306,2026-03-14,PH-01,Port Harcourt,In-store,Accessories,Phone Case,C1162,New,1,...,0.15,7650,3500.0,No,Aisha,7650.0,0.0,PASS,True,PASS
424,100367,2026-07-22,KN-01,Kano,In-store,Accessories,Phone Case,C1187,Returning,2,...,0.00,18000,3500.0,No,Kemi,18000.0,0.0,PASS,True,PASS
366,100367,2026-07-22,KN-01,Kano,In-store,Accessories,Phone Case,C1187,Returning,2,...,0.00,18000,3500.0,No,Kemi,18000.0,0.0,PASS,True,PASS
429,100386,2026-01-27,LG-01,Lagos,WhatsApp,Accessories,Phone Case,C1068,New,3,...,0.00,27000,3500.0,No,Ibrahim,27000.0,0.0,PASS,True,PASS
385,100386,2026-01-27,LG-01,Lagos,WhatsApp,Accessories,Phone Case,C1068,New,3,...,0.00,27000,3500.0,No,Ibrahim,27000.0,0.0,PASS,True,PASS
427,100395,2026-05-09,KN-01,Kano,WhatsApp,Accessories,Backpack,C1089,Returning,2,...,0.05,53200,16000.0,No,Aisha,53200.0,0.0,PASS,True,PASS
394,100395,2026-05-09,KN-01,Kano,WhatsApp,Accessories,Backpack,C1089,Returning,2,...,0.05,53200,16000.0,No,Aisha,53200.0,0.0,PASS,True,PASS
400,100401,2026-05-26,IB-01,Ibadan,Online,Electronics,Smartphone,C1158,Returning,3,...,0.00,495000,112000.0,Yes,Fatima,495000.0,0.0,PASS,True,PASS
431,100401,2026-05-26,IB-01,Ibadan,Online,Electronics,Smartphone,C1158,Returning,3,...,0.00,495000,112000.0,Yes,Fatima,495000.0,0.0,PASS,True,PASS

In [15]:
# Compare all column for each pair
duplicate_records.groupby("transaction_id").size()

transaction_id
100061    2
100074    2
100196    2
100197    2
100252    2
100276    2
100304    2
100306    2
100367    2
100386    2
100395    2
100401    2
dtype: int64

In [16]:
duplicate_records.groupby("transaction_id").nunique()

,date,store_id,state,channel,product_category,product,customer_id,customer_type,units,unit_price_ngn,discount_pct,revenue_reported_ngn,cost_per_unit_ngn,return_flag,sales_rep,expected_revenue_ngn,revenue_difference_ngn,revenue_validation,duplicate_transaction,category_validation
transaction_id,,,,,,,,,,,,,,,,,,,,
100061,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100074,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100196,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100197,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100252,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100276,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100304,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100306,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100367,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100386,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100395,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100401,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [17]:
# Remove duplicate transactions
duplicate_ids = (
    df.loc[df["duplicate_transaction"], "transaction_id"]
    .drop_duplicates()
)

duplicate_records = (
    df[df["transaction_id"].isin(duplicate_ids)]
    .sort_values("transaction_id")
)

duplicate_records

,transaction_id,date,store_id,state,channel,product_category,product,customer_id,customer_type,units,...,discount_pct,revenue_reported_ngn,cost_per_unit_ngn,return_flag,sales_rep,expected_revenue_ngn,revenue_difference_ngn,revenue_validation,duplicate_transaction,category_validation
60,100061,2026-08-17,LG-02,Lagos,In-store,Electronics,Earbuds,C1039,Returning,1,...,0.15,27200,19000.0,No,Aisha,27200.0,0.0,PASS,True,PASS
430,100061,2026-08-17,LG-02,Lagos,In-store,Electronics,Earbuds,C1039,Returning,1,...,0.15,27200,19000.0,No,Aisha,27200.0,0.0,PASS,True,PASS
73,100074,2026-04-20,IB-01,Ibadan,In-store,Accessories,USB Cable,C1043,New,4,...,0.05,24700,2200.0,No,Chinedu,24700.0,0.0,PASS,True,PASS
428,100074,2026-04-20,IB-01,Ibadan,In-store,Accessories,USB Cable,C1043,New,4,...,0.05,24700,2200.0,No,Chinedu,24700.0,0.0,PASS,True,PASS
195,100196,2026-02-25,LG-02,Lagos,In-store,Electronics,Earbuds,C1147,Returning,4,...,0.10,115200,19000.0,No,Grace,115200.0,0.0,PASS,True,PASS
421,100196,2026-02-25,LG-02,Lagos,In-store,Electronics,Earbuds,C1147,Returning,4,...,0.10,115200,19000.0,No,Grace,115200.0,0.0,PASS,True,PASS
196,100197,2026-08-01,AB-01,Abuja,Online,Accessories,Phone Case,C1152,Returning,1,...,0.25,6750,3500.0,Yes,Kemi,6750.0,0.0,PASS,True,PASS
420,100197,2026-08-01,AB-01,Abuja,Online,Accessories,Phone Case,C1152,Returning,1,...,0.25,6750,3500.0,Yes,Kemi,6750.0,0.0,PASS,True,PASS
425,100252,2026-07-11,KN-01,Kano,In-store,Electronics,Power Bank,C1117,Returning,2,...,0.00,52000,15000.0,No,David,52000.0,0.0,PASS,True,PASS
251,100252,2026-07-11,KN-01,Kano,In-store,Electronics,Power Bank,C1117,Returning,2,...,0.00,52000,15000.0,No,David,52000.0,0.0,PASS,True,PASS
426,100276,2026-06-22,LG-02,Lagos,Online,Home,Electric Kettle,C1016,New,2,...,0.10,43200,15000.0,No,David,43200.0,0.0,PASS,True,PASS
275,100276,2026-06-22,LG-02,Lagos,Online,Home,Electric Kettle,C1016,New,2,...,0.10,43200,15000.0,No,David,43200.0,0.0,PASS,True,PASS
303,100304,2026-07-01,KN-01,Kano,WhatsApp,Home,Standing Fan,C1090,New,5,...,0.10,261000,39000.0,No,Bola,261000.0,0.0,PASS,True,PASS
422,100304,2026-07-01,KN-01,Kano,WhatsApp,Home,Standing Fan,C1090,New,5,...,0.10,261000,39000.0,No,Bola,261000.0,0.0,PASS,True,PASS
305,100306,2026-03-14,PH-01,Port Harcourt,In-store,Accessories,Phone Case,C1162,New,1,...,0.15,7650,3500.0,No,Aisha,7650.0,0.0,PASS,True,PASS
423,100306,2026-03-14,PH-01,Port Harcourt,In-store,Accessories,Phone Case,C1162,New,1,...,0.15,7650,3500.0,No,Aisha,7650.0,0.0,PASS,True,PASS
424,100367,2026-07-22,KN-01,Kano,In-store,Accessories,Phone Case,C1187,Returning,2,...,0.00,18000,3500.0,No,Kemi,18000.0,0.0,PASS,True,PASS
366,100367,2026-07-22,KN-01,Kano,In-store,Accessories,Phone Case,C1187,Returning,2,...,0.00,18000,3500.0,No,Kemi,18000.0,0.0,PASS,True,PASS
429,100386,2026-01-27,LG-01,Lagos,WhatsApp,Accessories,Phone Case,C1068,New,3,...,0.00,27000,3500.0,No,Ibrahim,27000.0,0.0,PASS,True,PASS
385,100386,2026-01-27,LG-01,Lagos,WhatsApp,Accessories,Phone Case,C1068,New,3,...,0.00,27000,3500.0,No,Ibrahim,27000.0,0.0,PASS,True,PASS
427,100395,2026-05-09,KN-01,Kano,WhatsApp,Accessories,Backpack,C1089,Returning,2,...,0.05,53200,16000.0,No,Aisha,53200.0,0.0,PASS,True,PASS
394,100395,2026-05-09,KN-01,Kano,WhatsApp,Accessories,Backpack,C1089,Returning,2,...,0.05,53200,16000.0,No,Aisha,53200.0,0.0,PASS,True,PASS
400,100401,2026-05-26,IB-01,Ibadan,Online,Electronics,Smartphone,C1158,Returning,3,...,0.00,495000,112000.0,Yes,Fatima,495000.0,0.0,PASS,True,PASS
431,100401,2026-05-26,IB-01,Ibadan,Online,Electronics,Smartphone,C1158,Returning,3,...,0.00,495000,112000.0,Yes,Fatima,495000.0,0.0,PASS,True,PASS

In [18]:
duplicate_records.groupby("transaction_id").size()

transaction_id
100061    2
100074    2
100196    2
100197    2
100252    2
100276    2
100304    2
100306    2
100367    2
100386    2
100395    2
100401    2
dtype: int64

In [19]:
duplicate_records.groupby("transaction_id").nunique()

,date,store_id,state,channel,product_category,product,customer_id,customer_type,units,unit_price_ngn,discount_pct,revenue_reported_ngn,cost_per_unit_ngn,return_flag,sales_rep,expected_revenue_ngn,revenue_difference_ngn,revenue_validation,duplicate_transaction,category_validation
transaction_id,,,,,,,,,,,,,,,,,,,,
100061,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100074,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100196,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100197,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100252,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100276,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100304,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100306,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100367,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100386,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100395,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
100401,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [9]:
# Product to category validation
product_category = (
    df.groupby("product")["product_category"]
    .first()
    .str.strip()
    .str.title()
    .to_dict()
)

expected_category = df["product"].map(product_category)

df["category_validation"] = np.where(
    df["product_category"].str.strip().str.title()
    == expected_category,
    "PASS",
    "FAIL"
)
print(df["category_validation"])

0      PASS
1      PASS
2      PASS
3      PASS
4      PASS
       ...
427    PASS
428    PASS
429    PASS
430    PASS
431    PASS
Name: category_validation, Length: 432, dtype: object